[general]
test = "test"

[ScreenshotTaker]
monitor_number = 2

[MovementController]
offset_x = 0 # -1920
offset_y = 0

[AOIExtractor]
max_salvage_output = 5
save_images_with_detections = true

[Scrooper]
refference_point = [0.5, 0.3]